# Generated by Django 5.0.2 on 2024-02-08 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("specialization", models.CharField(max_length=200)),
                ("experience", models.IntegerField()),
                ("contact", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("working_hours", models.CharField(max_length=200)),
                ("license_number", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="experiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exptext", models.CharField(max_length=300)),
                (
                    "doctors",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.doctors",
                    ),
                ),
            ],
        ),
    ]
